name: Cache NDK
on:
  schedule:
    - cron: '0 0 * * 0'  # Haftada bir
  workflow_dispatch:

jobs:
  cache-ndk:
    runs-on: ubuntu-22.04
    steps:
    - name: Cache NDK 25b
      uses: actions/cache@v4
      with:
        path: ~/.buildozer/android/platform/android-ndk-r25b
        key: ndk-25b-${{ runner.os }}
